FROM ubuntu:22.04

# Set the working directory
WORKDIR /app

ENV LC_ALL=de_DE.UTF-8 \
    LANG=de_DE.UTF-8 \
    LANGUAGE=de_DE.UTF-8

# Install system dependencies
RUN apt-get update \
    && apt upgrade -y \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt install -y software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa -y \
    && apt update

RUN apt install -y python3.10 python3-pip 

#RUN dpkg-reconfigure locales

RUN python3 -m pip install nicegui pywebview shellsmith python-dateutil

# Copy application files
COPY . .

# Define the command to run the app
CMD ["sh", "-c", "python3 aas_parser/synchronizer.py & python3 main.py & wait"]

# docker build -t dace_dpp .
# docker run --network=host dace_dpp 